name: CI - Pull Requests

on:
    pull_request:
        branches:
            - master

jobs:
    verify-build-and-tests:
        runs-on: ubuntu-latest

        steps:
            - name: CHECKOUT REPOSITORY
              uses: actions/checkout@v3

            - name: START CONTAINERS
              run: docker compose up -d

            - name: CHECK RUNNING CONTAINERS
              run: |
                  docker container ps -a
                  docker container logs app
                  docker container ls -a
                  docker compose top

            - name: EXEC TESTS
              run: docker container exec app yarn test unit

            - name: STOP CONTAINERS
              run: docker compose down
