name: CI - Pull Requests

on:
    pull_request:
        branches:
            - master

jobs:
    verify-build-and-tests:
        runs-on: ubuntu-latest

        steps:
            - name: CHECKOUT REPOSITORY
              uses: actions/checkout@v3

            - name: START CONTAINERS
              run: docker compose up -d

            - name: CHECK RUNNING CONTAINERS
              run: docker compose ps -a

            - name: CHECK APP LOGS
              run: docker compose logs app

            - name: EXEC TESTS
              run: docker compose exec app yarn test

            - name: STOP CONTAINERS
              run: docker compose down
