name: CI - Pull Requests

on:
    pull_request:
        branches:
            - master

jobs:
    verify-build-and-tests:
        runs-on: ubuntu-latest

        steps:
            - name: CHECKOUT REPOSITORY
              uses: actions/checkout@v3

            - name: SETUP NODEJS
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'

            - name: INSTALL | BUILD | CONTAINERS
              run: |
                  docker compose up -d

                  sleep 30

            - name: EXEC UNIT TESTS
              run: |
                  docker compose exec app bash

                  yarn test unit

            - name: STOP DOCKER CONTAINERS
              run: docker compose down
