name: CI - Pull Requests

on:
    pull_request:
        branches:
            - master

jobs:
    verify-build-and-tests:
        runs-on: ubuntu-latest

        steps:
            - name: CHECKOUT REPOSITORY
              uses: actions/checkout@v3

            - name: START CONTAINERS
              run: docker compose up -d

            - name: CHECK RUNNING CONTAINERS
              run: |
                  docker container ps -a
                  docker container logs app
                  docker container ls -a
                  docker compose top

            - name: SETUP NODEJS
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
            - run: docker container start app
            - run: docker container exec app yarn install
            - run: docker container exec app yarn build
            - run: docker container exec app yarn dev
            - run: docker container exec app yarn test unit

            - name: STOP CONTAINERS
              run: docker compose down
